---
title: "Codebook"
author: "Suhas P K"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. 
Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. 
Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. 
The experiments have been video-recorded to label the data manually. 
The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data 
and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). 
The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. 
The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. 
From each window, a vector of features was obtained by calculating variables from the time and frequency domain. 
See 'features_info.txt' for more details. 

For each record it is provided:
======================================

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

The dataset includes the following files:
=========================================

- 'README.txt'

- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of all features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.

The following files are available for the train and test data. Their descriptions are equivalent. 

- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

- 'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 

- 'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration. 

- 'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second. 


The run_analysis.R script prepare and download the data and then follows the steps as described

    Dataset is Downloaded and extracted under the folder called UCI HAR Dataset

    -> Assigns each data to variables:
    1. features <- features.txt (from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ.) 
    2. activities <- activity_labels.txt (List of activities performed when the corresponding measurements were taken and its labels) 
    3. subject_test <- test/subject_test.txt (test data of 9/30 volunteer test subjects)
    4. x_test <- test/X_test.txt (features test data) 
    5. y_test <- test/y_test.txt (test data of activities'ID labels) 
    6. subject_train <- test/subject_train (train data of 21/30 volunteer subjects) 
    7. x_train <- test/X_train.txt (features train data) 
    8. y_train <- test/y_train.txt (train data of activities’ID labels)

    -> Merges the traing and test sets using rbind() and cbind() to create one dataset
        subject <- rbind(subjectTrain, subjectTest)
        activity <- rbind(y_Train, y_Test)
        features <- rbind(x_Train, x_Test)
        
    -> From the new dataset extracts only the mean and standard devaition for each measurement.
    colnames(features) <- featureNames[,2]
    colnames(activity) <- "Activity"
    colnames(subject) <- "Subject"
    completeData <- cbind(features,activity,subject)
    View(completeData)
    columnsWithMeanSTD <- grep(".*Mean.*|.*Std.*", names(completeData), ignore.case=TRUE)
    View(columnsWithMeanSTD))

    -> Descriptive activity names to name the activities in dataset and Replace the labels with descriptive names and correct the typos
    names(extractedData)<-gsub("Acc", "Accelerometer", names(extractedData))
    names(extractedData)<-gsub("Gyro", "Gyroscope", names(extractedData))
    names(extractedData)<-gsub("BodyBody", "Body", names(extractedData))
    names(extractedData)<-gsub("Mag", "Magnitude", names(extractedData))
    names(extractedData)<-gsub("^t", "Time", names(extractedData))
    names(extractedData)<-gsub("^f", "Frequency", names(extractedData))
    names(extractedData)<-gsub("tBody", "TimeBody", names(extractedData))
    names(extractedData)<-gsub("-mean()", "Mean", names(extractedData), ignore.case = TRUE)
    names(extractedData)<-gsub("-std()", "STD", names(extractedData), ignore.case = TRUE)
    names(extractedData)<-gsub("-freq()", "Frequency", names(extractedData), ignore.case = TRUE)
    names(extractedData)<-gsub("angle", "Angle", names(extractedData))
    names(extractedData)<-gsub("gravity", "Gravity", names(extractedData))
    
    
    names(extractedData)
    
    extractedData$Subject <- as.factor(extractedData$Subject)
    extractedData <- data.table(extractedData)
    
    -> From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject TidyData is created
    tidyData <- aggregate(. ~Subject + Activity, extractedData, mean)
    tidyData <- tidyData[order(tidyData$Subject,tidyData$Activity),]
    View(tidyData)
    write.table(tidyData, file = "Tidy.txt", row.names = FALSE)


